AWSTemplateFormatVersion: 2010-09-09
Description: Creates the basic Networking components.
Parameters:
  TagProjectName:
    Type: String
    Description: Project Name
  VPCName:
    Type: String
    Description: VPC Name
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value:
            Ref: VPCName
        - Key: Project
          Value:
            Ref: TagProjectName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: !Sub 
            - '${VPCName}_internet_gateway'
            - VPCName: !Ref VPCName
        - Key: Project
          Value:
            Ref: TagProjectName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags:
        - Key: Name
          Value: !Sub 
            - '${VPCName}_route_table'
            - VPCName: !Ref VPCName
        - Key: Project
          Value:
            Ref: TagProjectName
      VpcId:
        Ref: VPC

  InternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTable

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: AWS::Region
      CidrBlock: 10.0.0.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags:
        - Key: InternetAccess
          Value: Inbound
        - Key: Name
          Value: !Sub 
            - '${VPCName}_public_subnet_a'
            - VPCName: !Ref VPCName
        - Key: Project
          Value:
            Ref: TagProjectName
        - Key: SubnetType
          Value: Public
      VpcId:
        Ref: VPC

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: AWS::Region
      CidrBlock: 10.0.1.0/24
      EnableDns64: false
      MapPublicIpOnLaunch: true
      Tags:
        - Key: InternetAccess
          Value: Inbound
        - Key: Name
          Value: !Sub 
            - '${VPCName}_public_subnet_b'
            - VPCName: !Ref VPCName
        - Key: Project
          Value:
            Ref: TagProjectName
        - Key: SubnetType
          Value: Public
      VpcId:
        Ref: VPC

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: PublicSubnet2

  # PrivateSubnet1:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone:
  #       Fn::Select:
  #         - 2
  #         - Fn::GetAZs: ''
  #     CidrBlock: 10.0.2.0/24
  #     EnableDns64: false
  #     MapPublicIpOnLaunch: false
  #     Tags:
  #       - Key: InternetAccess
  #         Value: Outbound
  #       - Key: Project
  #         Value:
  #           Ref: TagProjectName
  #       - Key: SubnetType
  #         Value: Private
  #       - Key: Name
  #         Value: PrivateSubnet1
  #     VpcId:
  #       Ref: VPC
  # PrivateSubnet2:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AvailabilityZone:
  #       Fn::Select:
  #         - 3
  #         - Fn::GetAZs: ''
  #     CidrBlock: 10.0.3.0/24
  #     EnableDns64: false
  #     MapPublicIpOnLaunch: false
  #     Tags:
  #       - Key: InternetAccess
  #         Value: NonInternetAccess
  #       - Key: Project
  #         Value:
  #           Ref: TagProjectName
  #       - Key: SubnetType
  #         Value: Private
  #       - Key: Name
  #         Value: PrivateSubnet2
  #     VpcId:
  #       Ref: VPC
